export const FILTER_DATA = 'FILTER_DATA';
export const FETCHING_DATA = 'FETCHING_DATA';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_ERR = 'FETCH_DATA_ERR';
export const SORTDIRECTION_DATA = 'SORTDIRECTION_DATA';
export const FETCH_MORE_DATA_SUCCESS = 'FETCH_MORE_DATA_SUCCESS';
